In [1]:
import pandas as pd

In [2]:
# Load the dataset
data = pd.read_csv('newmodified_dataset.csv')

In [3]:
data.head()

,District_Name,UnitName,FIR Type,FIR_Stage,Complaint_Mode,CrimeGroup_Name,CrimeHead_Name,Latitude,Longitude,ActSection,...,Age 0,VICTIM COUNT,Accused Count,Arrested Male,Arrested Female,Arrested Count\tNo.,Accused_ChargeSheeted Count,Conviction Count,Unit_ID,Crime_No
0,Bagalkot,Amengad PS,Non Heinous,Dis/Acq,Written,POCSO,Others,0.0,0.0,PROTECTION OF CHILDREN FROM SEXUAL OFFENCES AC...,...,0,0,1,1,0,1,1,0,1245,10470124520160001
1,Bagalkot,Amengad PS,Non Heinous,Convicted,Sue-moto by Police,KARNATAKA POLICE ACT 1963,Street Gambling (87),0.0,0.0,"KARNATAKA POLICE ACT, 1963 U/s: 87",...,0,0,5,5,0,5,5,2,1245,10470124520160002
2,Bagalkot,Amengad PS,Non Heinous,Convicted,Sue-moto by Police,KARNATAKA POLICE ACT 1963,Gambling - Matka (78 Class C),0.0,0.0,"KARNATAKA POLICE ACT, 1963 U/s: 78(3)",...,0,0,1,1,0,1,1,0,1245,10470124520160003
3,Bagalkot,Amengad PS,Non Heinous,Convicted,Written,MOTOR VEHICLE ACCIDENTS NON-FATAL,National Highways,0.0,0.0,"IPC 1860 U/s: 338,337,279",...,1,0,1,1,0,1,1,0,1245,10470124520160004
4,Bagalkot,Amengad PS,Heinous,Pending Trial,Written,MOTOR VEHICLE ACCIDENTS FATAL,Other Roads,0.0,0.0,"IPC 1860 U/s: 304(A),279",...,0,0,1,1,0,1,1,0,1245,10470124520160005

In [ ]:
# Group the data by location and sum the accused counts
total_accused_count_by_location = data.groupby('Location')['Accused_Count'].sum()

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 28 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   District_Name                1000 non-null   object
 1   UnitName                     1000 non-null   object
 2   FIR Type                     1000 non-null   object
 3   FIR_Stage                    1000 non-null   object
 4   Complaint_Mode               987 non-null    object
 5   CrimeGroup_Name              1000 non-null   object
 6   CrimeHead_Name               1000 non-null   object
 7   Latitude                     1000 non-null   float64
 8   Longitude                    1000 non-null   float64
 9   ActSection                   1000 non-null   object
 10  Place of Offence             1000 non-null   object
 11  Distance from PS             1000 non-null   object
 12  Beat_Name                    1000 non-null   object
 13  Village_Area_Name            1000 non-null   object
 14  Male                         1000 non-null   int64
 15  Female                       1000 non-null   int64
 16  Boy                          1000 non-null   int64
 17  Girl                         1000 non-null   int64
 18  Age 0                        1000 non-null   int64
 19  VICTIM COUNT                 1000 non-null   int64
 20  Accused Count                1000 non-null   int64
 21  Arrested Male                1000 non-null   int64
 22  Arrested Female              1000 non-null   int64
 23  Arrested Count	No.           1000 non-null   int64
 24  Accused_ChargeSheeted Count  1000 non-null   int64
 25  Conviction Count             1000 non-null   int64
 26  Unit_ID                      1000 non-null   int64
 27  Crime_No                     1000 non-null   int64
dtypes: float64(2), int64(14), object(12)
memory usage: 218.9+ KB

In [5]:
# Group the data by location and sum the accused counts
total_accused_count_by_location = data.groupby('Village_Area_Name')['Accused Count'].sum()

In [6]:
total_accused_count_by_location

Village_Area_Name
AIHOLE           407
AMBLIKOPPA         5
AMINAGAD         366
BASANAL            2
BASARIKATTI        1
BENAL              3
CHIKKAMAGI         2
DAMMUR           394
GUDUR            241
KALLIGUDDA         0
KAMATAGI         384
KAMATAGI ONE      33
KELUR             24
KYADIGERI          1
MADAPUR          328
MURUDI            26
RAKKASAGI          5
RAMATHAL          13
SIDDANAKOLLA      14
SULEBAVI         292
SULEBHAVI TWO      4
UPANAL           252
Name: Accused Count, dtype: int64